### ISSUE TITLE
Changed SONAME in 1.4.4 creates problems downstream

### ISSUE THREAD

**Issue by zklaus** [conda-forge/rhash-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The SONAME change introduced in 1.4.4 creates problems downstream, see e.g. conda-forge/cmake-feedstock#192. Perhaps a migrator would be a good idea? Also repodata patches for downstream packages could be needed.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by xylar** [comment]
I believe we're seeing this in:
https://github.com/conda-forge/gdal-feedstock/pull/803
https://github.com/conda-forge/netcdf-fortran-feedstock/pull/84

At the very lease, these PRs are seeing issues with rhash that seem to be new since yesterday.

**Comment by zklaus** [comment]
@xylar, I think you are right, but it is by proxy via Cmake. The latest Cmake build (which is only 1 hour old) should work, so I believe for the immediate problem it's enough to restart the ci.

**Comment by h-vetinari** [comment]
Should we not raise an issue for this upstream? Why was the SONAME bumped in a patch release?

**Comment by zklaus** [comment]
Hm. I guess as long as the project hasn't committed to a certain versioning strategy, there isn't really anything wrong with it, though it certainly is a bit surprising.

Anyway, I am gonna close this issue because @isuruf solved it with repodata patches. In fact he thought of the issue before it occurred and was careful enough to put the appropriate patch (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/531) in before making the SONAME/SOVERSION change. Unfortunately a small problem crept in which was then later rectified by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/533, so now all should be good.
